// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1HXi2ecV0ZUWhRPMqrTHd-5xUK22Tisc',
    appId: '1:427171164264:web:d68411f4950b23507fcbdd',
    messagingSenderId: '427171164264',
    projectId: 'my-flutter-97db9',
    authDomain: 'my-flutter-97db9.firebaseapp.com',
    storageBucket: 'my-flutter-97db9.firebasestorage.app',
    measurementId: 'G-FT7EBP7S8M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI6plG6eyEaputlDFl9zYvJDbYDRtgOqY',
    appId: '1:427171164264:android:773a1d97cb6a6a7c7fcbdd',
    messagingSenderId: '427171164264',
    projectId: 'my-flutter-97db9',
    storageBucket: 'my-flutter-97db9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7dyYMbz3jLUtnWxbI24IoRLaMDpsFiLc',
    appId: '1:427171164264:ios:893a1304398f15787fcbdd',
    messagingSenderId: '427171164264',
    projectId: 'my-flutter-97db9',
    storageBucket: 'my-flutter-97db9.firebasestorage.app',
    iosBundleId: 'com.example.firebaseCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7dyYMbz3jLUtnWxbI24IoRLaMDpsFiLc',
    appId: '1:427171164264:ios:893a1304398f15787fcbdd',
    messagingSenderId: '427171164264',
    projectId: 'my-flutter-97db9',
    storageBucket: 'my-flutter-97db9.firebasestorage.app',
    iosBundleId: 'com.example.firebaseCrud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1HXi2ecV0ZUWhRPMqrTHd-5xUK22Tisc',
    appId: '1:427171164264:web:cd992e6ebf2f40cf7fcbdd',
    messagingSenderId: '427171164264',
    projectId: 'my-flutter-97db9',
    authDomain: 'my-flutter-97db9.firebaseapp.com',
    storageBucket: 'my-flutter-97db9.firebasestorage.app',
    measurementId: 'G-CE890T09ML',
  );
}
